<?php

namespace SmartUnity\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * commentaireReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentaireReponseRepository extends EntityRepository
{
}