<?php

namespace SmartUnity\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * commentaireReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentaireReponseRepository extends EntityRepository
{
	public function getMembresCommentedAnswer($reponseid) {
		$em = $this->getEntityManager();
		$query = $em->createQuery(
    	'SELECT DISTINCT IDENTITY (cr.membre)
    	FROM SmartUnityAppBundle:commentaireReponse cr
    	WHERE cr.reponse = :reponse'
		)->setParameter('reponse', $reponseid);

		$membres = $query->getResult();
		return $membres;
	}
}

