<?php

namespace SmartUnity\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * commentaireQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentaireQuestionRepository extends EntityRepository
{
    	public function getMembresCommentedQuestion($questionId) {
		$em = $this->getEntityManager();
		$query = $em->createQuery(
    	'SELECT DISTINCT IDENTITY (cq.membre)
    	FROM SmartUnityAppBundle:commentaireQuestion cq
    	WHERE cq.question = :question'
		)->setParameter('question', $questionId);

		$membres = $query->getResult();
		return $membres;
	}
}