<?php

namespace SmartUnity\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends EntityRepository
{

    public function getSmartReponses($membreId)
    {
        $query = $this->_em->createQuery('
            SELECT COUNT(r.id)
            FROM
            SmartUnityAppBundle:reponse r
            WHERE r.membre = :membreId
            AND r.dateCertification IS NOT NULL
            ')
            ->setParameter('membreId', $membreId);

        $result = $query->getScalarResult();

        return $result[0][1];

    }

    public function getRemuneration($membreId)
    {
        $query = $this->_em->createQuery('
			SELECT SUM(q.remuneration)	
            FROM
            SmartUnityAppBundle:reponse r, SmartUnityAppBundle:question q
            WHERE r.membre = :membreId
            AND r.dateValidation IS NOT NULL AND r.question=q.id
            ')
            ->setParameter('membreId', $membreId);


        $result = $query->getScalarResult();

        return $result[0][1] ;
    }


    
    

}