<?php

namespace SmartUnity\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * questionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class questionRepository extends EntityRepository
{
    
    public function getNombreQuestions(){

    	$qb= $this->createQueryBuilder('SmartUnityAppBundle:question')
    				->select('COUNT(SmartUnityAppBundle:question)');

		return $qb->getQuery()->getSingleScalarResult();

    }

}