<?php

namespace SmartUnity\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * reponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reponseRepository extends EntityRepository
{

	public function getBestReponse($QuestionId){

		/* $qb= $this->createQueryBuilder('SmartUnityAppBundle:noteReponse')
    				->select('SUM(SmartUnityAppBundle:noteReponse.note)')
    				->where('SmartUnityAppBundle:noteReponse.reponse = :id_reponse')
    				->setParameter('id_reponse', $QuestionId); */


        $query = $this->_em->createQuery('
            SELECT SmartUnityAppBundle:reponse.id AS repId, SUM( SmartUnityAppBundle:noteReponse.note ) AS somme
            FROM SmartUnityAppBundle:reponse
            LEFT JOIN SmartUnityAppBundle:noteReponse ON SmartUnityAppBundle:reponse.id = SmartUnityAppBundle:noteReponse.reponse_id
            WHERE SmartUnityAppBundle:question.question_id = :QuestionId
            GROUP BY SmartUnityAppBundle:reponse.id
            ORDER BY somme DESC
            LIMIT 0 , 1
            ')
            ->setParameter('QuestionId', $QuestionId);

        return $query->getResult();


        /* RECUP L'id de la réponse la mieux notée pour cette question ($QuestionId)

        SELECT reponse.id AS repId, SUM( noteReponse.note ) AS somme
        FROM reponse
        LEFT JOIN noteReponse ON reponse.id = noteReponse.reponse_id
        WHERE reponse.question_id = '1'
        GROUP BY reponse.id
        ORDER BY somme DESC
        LIMIT 0 , 1 */

	}
}