fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"  
    
smart_unity_question_reponse:
    resource: "@SmartUnityQuestionReponseBundle/Resources/config/routing.yml"

smart_unity_utilisateur:
    resource: "@SmartUnityUtilisateurBundle/Resources/config/routing.yml"

smart_unity_boutique:
    resource: "@SmartUnityBoutiqueBundle/Resources/config/routing.yml"
    prefix:   /Boutique/

smart_unity_app:
    resource: "@SmartUnityAppBundle/Resources/config/routing.yml"
    
_security_check:
    pattern:  /login_check
    defaults: { _controller: SmartUnityAppBundle:Accueil:loginCheck }

_security_logout:
    pattern:  /logout
    defaults: { _controller: SmartUnityAppBundle:Accueil:logout }

_facebook_secured:
    pattern: /secured
    defaults: { _controller: SmartUnityAppBundle:Accueil:index }
    
fos_facebook_channel:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml" 
    
elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"    




   

