security:
    encoders:
        SmartUnity\AppBundle\Entity\membre: sha512

    role_hierarchy:
        ROLE_MODERATEUR1: ROLE_USER
        ROLE_MODERATEUR2: [ROLE_USER, ROLE_MODERATEUR1]
        ROLE_ADMIN:       [ROLE_USER, ROLE_MODERATEUR1, ROLE_MODERATEUR2]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_MODERATEUR1, ROLE_MODERATEUR2, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/Admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
