security:
    encoders:
        SmartUnity\AppBundle\Entity\membre: sha512

    role_hierarchy:
        ROLE_MODERATEUR1: ROLE_USER
        ROLE_MODERATEUR2: [ROLE_USER, ROLE_MODERATEUR1]
        ROLE_ADMIN:       [ROLE_USER, ROLE_MODERATEUR1, ROLE_MODERATEUR2]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_MODERATEUR1, ROLE_MODERATEUR2, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [main, my_fos_facebook_provider]
        main:
            id: fos_user.user_provider.username_email
        my_fos_facebook_provider:
            id: my.facebook.user  

        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                target_path_parameter: _target_path
                use_referer:        true
                default_target_path: /
                
            fos_facebook:
                app_url: "http://apps.facebook.com/smartunity/"
                server_url: "http://local.smartunity.com/~Yvan/workspace/smartunity_remy_12112013/web/app_dev.php"
                check_path: /login_check
                provider: my_fos_facebook_provider
                
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml
                

            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/Admin/, roles: ROLE_ADMIN }
        - { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY] } # This is the route secured with fos_facebook
        - { path: ^/Utilisateur/mon-compte, role: ROLE_USER }
        - { path: ^/efconnect, role: ROLE_USER }
        - { path: ^/elfinder, role: ROLE_USER }
        - { path: ^/.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
