smart_unity_utilisateur_setinfos:
    pattern:  /modify_infos
    defaults: { _controller: SmartUnityUtilisateurBundle:Utilisateur:setInfos }

smart_unity_utilisateur_editinfos:
    pattern:  /edit_infos
    defaults: { _controller: SmartUnityUtilisateurBundle:Utilisateur:editInfos }

smart_unity_utilisateur_editavatar:
    pattern:  /upload_avatar
    defaults: { _controller: SmartUnityUtilisateurBundle:Utilisateur:upload }    

smart_unity_utilisateur_changepassword:
    pattern:  /change_password
    defaults: { _controller: SmartUnityUtilisateurBundle:ChangePassword:changePassword }
    
smart_unity_utilisateur_setpref:
    pattern:  /modify_pref
    defaults: { _controller: SmartUnityUtilisateurBundle:Utilisateur:setPref }

smart_unity_utilisateur_homepage:
    pattern:  /
    defaults: { _controller: SmartUnityUtilisateurBundle:Utilisateur:index }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /Utilisateur

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profil   

