smart_unity_utilisateur_setinfos:
    pattern:  /modify_infos
    defaults: { _controller: SmartUnityUtilisateurBundle:Default:setInfos }

smart_unity_utilisateur_editinfos:
    pattern:  /edit_infos
    defaults: { _controller: SmartUnityUtilisateurBundle:Default:indexWithEditInfos }

smart_unity_utilisateur_setpref:
    pattern:  /modify_pref
    defaults: { _controller: SmartUnityUtilisateurBundle:Default:setPref }

smart_unity_utilisateur_homepage:
    pattern:  /
    defaults: { _controller: SmartUnityUtilisateurBundle:Default:index }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /Utilisateur

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profil    

