parameters:
#    smart_unity_utilisateur.example.class: SmartUnity\UtilisateurBundle\Example

services:
   smart_unity_app.registration.form.type:
        class:  SmartUnity\UtilisateurBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: smartunity_user_registration }
   
   smart_unity_app.pref.form.type:
        class:  SmartUnity\UtilisateurBundle\Form\Type\PreferenceFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: smartunity_user_preference }
   
   smart_unity_app.infos.form.type:
        class:  SmartUnity\UtilisateurBundle\Form\Type\InformationsFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: smartunity_user_informations }  

   smart_unity_app.parrainage.form.type:
        class:  SmartUnity\UtilisateurBundle\Form\Type\ParrainageFormType
        tags:
            - { name: form.type, alias: smartunity_user_parrainage }   
            
   utilisateur.twig.utilisateur_extension:
        class: SmartUnity\UtilisateurBundle\Twig\utilisateurExtension
        tags:
            - { name: twig.extension }

   smart_unity_app.type.hidden_entity:
        class: SmartUnity\UtilisateurBundle\Form\Type\HiddenEntityType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: hidden_entity }