parameters:
#    smart_unity_utilisateur.example.class: SmartUnity\UtilisateurBundle\Example

services:
#    smart_unity_utilisateur.example:
#        class: %smart_unity_utilisateur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
