parameters:

services:

   smart_unity_app.contact.form.type:
        class:  SmartUnity\AppBundle\Form\Type\ContactFormType
        tags:
            - { name: form.type, alias: smart_unity_app_contact }
            
   smart_unity_app.mailer:
      class: SmartUnity\AppBundle\Mail\Mailer
      arguments: [@mailer, @templating, %kernel.root_dir%]
      
   elfinder.driver.filesystem:
      class: FM\ElFinderPHP\Driver\ElFinderVolumeLocalFileSystem  
           