parameters:
    smart_unity_app.example.class: SmartUnity\AppBundle\Form\Type\RegistrationFormType

services:
   smart_unity_app.form.type:
        class: [%smart_unity_app.example.class%]
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: smartunity_user_registration }
