parameters:
#    smart_unity_admin.example.class: SmartUnity\AdminBundle\Example

services:
#    smart_unity_admin.example:
#        class: %smart_unity_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
