parameters:
#    smart_unity_boutique.example.class: SmartUnity\BoutiqueBundle\Example

services:
#    smart_unity_boutique.example:
#        class: %smart_unity_boutique.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
