parameters:
#    smart_unity_blog.example.class: SmartUnity\BlogBundle\Example

services:
#    smart_unity_blog.example:
#        class: %smart_unity_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
