smart_unity_question_reponse_list_of_question:
    pattern:  /questions/{type}/{page}
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:displayListOfQuestion, type:'last', page:'1' }
    requirements:
        type: onFire|last|reponses|question
        page: \d+

smart_unity_question_reponse_demander_questions:
    pattern: /recherche/
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:searchDemanderQuestion }

smart_unity_question_reponse_repondre_questions:
    pattern: /recherche-filtres/{page}
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:searchRepondreQuestion, page:'1' }
    
smart_unity_question_reponse_display_reponse:

    pattern:  /question/{slug}/{tri}/{page}
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:displayReponse, page:'1', slug:'', tri:'vote' }
    requirements:
        tri: vote|date
        page: \d+

smart_unity_question_reponse_add_question:
    pattern:  /ajouter-question/
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:addQuestion }
    
smart_unity_question_reponse_edit_question:
    pattern:  /editer-question/{slug}/
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:editQuestion }    

smart_unity_question_reponse_add_reponse:
    pattern:  /ajouter-reponse/{slug}/
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:addReponse, slug:''}

smart_unity_question_reponse_editer_reponse:
    pattern: /editer-reponse/{slug}/{id}
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:editReponse}

smart_unity_question_reponse_supprimer_reponse:
    pattern: /supprimer-reponse/{slug}/{id}
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:SupprimerReponse}
    options:
        expose: true
    
smart_unity_question_reponse_validation_reponse:
    pattern:  /validation/{idReponse}
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:validationReponse }
    options:
        expose: true
        
smart_unity_question_reponse_certification:
    pattern:  /certification/{idReponse}
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:certificationReponse }
    options:
        expose: true

smart_unity_question_reponse_add_commentaire_question:
    pattern:  /ajouter-comm-question/{slug}/
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:addCommentaireQuestion }

smart_unity_question_reponse_add_commentaire_reponse:
    pattern:  /ajouter-comm-reponse/{slug}/{idReponse}
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:addCommentaireReponse }
    requirements:
        idReponse: \d+

smart_unity_question_reponse_add_soutien_question:
    pattern:  /ajouter-soutien/{slug}/
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:addSoutienQuestion }

smart_unity_question_reponse_signaler_question:
    pattern:  /signaler-question/{slug}
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:signalerQuestion }

smart_unity_question_reponse_signaler_reponse:
    pattern:  /signaler-reponse/{idReponse}
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:signalerReponse }
    requirements:
        idReponse: \d+
    options:
        expose: true

smart_unity_question_reponse_signaler_commentaire_question:
    pattern:  /signaler-commentaireQuestion/{idCommentaireQuestion}/
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:signalerCommentaireQuestion }
    requirements:
        idCommentaireQuestion: \d+

smart_unity_question_reponse_signaler_commentaire_reponse:
    pattern:  /signaler-commentaireReponse/{idCommentaireReponse}/
    defaults: { _controller: SmartUnityQuestionReponseBundle:QuestionReponse:signalerCommentaireReponse }
    requirements:
        idCommentaireReponse: \d+
    options:
        expose: true

######################
#### AJAX ROUTING ####
######################

smart_unity_question_reponse_ajax_get_questions:
    pattern: /getQuestions/{type}/{page}/{nbParPage}
    defaults: { _controller: SmartUnityQuestionReponseBundle:Ajax:getQuestions, type:'reponses', page:'1', nbParPage:'3'}
    requirements:
        type: onFire|last|reponses|question
        page: \d+
        nbParPage: \d+

smart_unity_question_reponse_ajax_get_reponses:
    pattern: /getReponses/{slug}/{tri}/{page}/{nbParPage}
    defaults: { _controller: SmartUnityQuestionReponseBundle:Ajax:getReponses, tri:'vote', page:'1', nbParPage:'5'}
    requirements:
        page: \d+
        nbParPage: \d+
        tri: vote|date

smart_unity_question_reponse_ajax_upvote:
    pattern: /setUpVote/{reponseId}
    defaults: { _controller: SmartUnityQuestionReponseBundle:Ajax:setUpVote, reponseId:'0'}
    requirements:
        reponse: \d+

smart_unity_question_reponse_ajax_downvote:
    pattern: /setDownVote/{reponseId}
    defaults: { _controller: SmartUnityQuestionReponseBundle:Ajax:setDownVote, reponseId:'0'}
    requirements:
        reponse: \d+
