parameters:
#    smart_unity_question_reponse.example.class: SmartUnity\QuestionReponseBundle\Example

services:
    
   smart_unity_app.filtres.form.type:
        class:  SmartUnity\QuestionReponseBundle\Form\Type\FiltresRepondreFormType
        tags:
            - { name: form.type, alias: smartunity_filtres_repondre }
