parameters:
#    smart_unity_question_reponse.example.class: SmartUnity\QuestionReponseBundle\Example

services:
#    smart_unity_question_reponse.example:
#        class: %smart_unity_question_reponse.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
