parameters:
#    smart_unity_forum.example.class: SmartUnity\ForumBundle\Example

services:
#    smart_unity_forum.example:
#        class: %smart_unity_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
